server:
  port: 8080
spring:
  application:
    name: mission
  config:
    import: optional:file:.env[.properties]
  profiles:
    active: dev
  output:
    ansi:
      enabled: always
  jackson:
    serialization:
      fail-on-empty-beans: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:mission}?createDatabaseIfNotExist=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 100
logging:
  level:
    com.back: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
    org.springframework.transaction.interceptor: TRACE

custom:
  global:
    internalBackUrl: http://localhost:${server.port:8080}
  member:
    password:
      changeDays: 90